[package]
name = "stdout-channel"
version = "0.1.2"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
deadqueue = "0.1"
tokio = {version="0.3", features=["io-std", "io-util", "sync", "rt-multi-thread"]}
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.1.9", features=["postgres_types"] }

[dev-dependencies]
tokio = {version="0.3", features=["rt-multi-thread", "macros"]}